# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c5acdf203adbfae301cab6981b8cbee0df8e884c474d097c0e461364a70155b49048df0296a64220f876740a9fccf4bafa5a996841b942b550a730d1e75d693

test:
  secret_key_base: 1a99c206c7eb23480b19d1f1bdcbb3cf6b6d91c22859859b9b1e3e7dda95821d730efebe7cfef44da8d141da89735e2a26b9557cbe142a50b2dd4e06ffad84d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
